"""Loader + cleaner for the SIH-2026 Annapurna CSV bundle.

    python ml_data_load_sih2026.py            # load, clean, report
    python ml_data_load_sih2026.py --info-only

This is the single place that knows the CSV schema, so no training script has to
re-implement the cleaning rules.  The rules come from ``data_dictionary.md`` and are
not negotiable:

1.  ``latent_*`` columns are ground truth for EVALUATION ONLY.  :func:`assert_no_latent`
    is called by every trainer so a leak cannot slip in silently.
2.  ``dq_flag`` rows are dropped for training (missing sales, x10 unit errors, stale
    copies, duplicates, sensor glitches, Fahrenheit rows) and counted in the report.
3.  ``units_sold`` is CENSORED by stock: ``stockout_flag=1`` rows under-state demand.
    Censored rows are excluded from the training target rather than trained on as
    truth -- training on a censored target teaches the model to under-predict exactly
    when a kitchen is busiest.
4.  ``closed`` days are excluded; a planned or unplanned closure is not a low-demand
    day, it is a day with no service at all.
5.  Kitchen-less sensors and loggers without temp sensors produce NaNs *by design*
    (85% missing for kitchens with no logger).  Those NaNs are kept and surfaced as a
    missingness feature -- filling them with a mean would invent an observation.

Every table keeps ``data_source`` so a metrics artefact can never silently imply real
kitchen data.
"""

from __future__ import annotations

import argparse
from pathlib import Path

if __package__ in (None, ""):  # pragma: no cover
    import sys

    sys.path.insert(0, str(Path(__file__).resolve().parent))

import numpy as np
import pandas as pd

from ml_utils import get_logger, get_paths, save_json

LOG = get_logger("data.sih2026")

#: Raw rows whose ``dq_flag`` is not "ok" are unusable as training targets.
DEMAND_BAD_DQ = ("missing_sales", "unit_error_x10", "stale_copy", "duplicate")
BATCH_BAD_DQ = ("sensor_glitch", "unit_error_fahrenheit")
SENSOR_BAD_DQ = ("data_gap",)

#: Columns the data dictionary marks as outcomes, not features.
DEMAND_OUTCOMES = (
    "prepared_units", "units_sold", "leftover_units", "leftover_kg",
    "stockout_flag", "is_closed", "outage_flag", "latent_true_demand", "row_id",
)
BATCH_EVAL_ONLY = (
    "latent_p_unsafe", "latent_spoilage_consumed", "latent_log10_pathogen",
    "cold_chain_break", "batch_id", "prep_timestamp",
)
SENSOR_EVAL_ONLY = ("is_anomaly", "anomaly_type")

#: Backward-looking lags, in days.  364 is year-over-year and is NaN early in the
#: bundle -- LightGBM splits on missing natively, so no imputation is invented.
DEMAND_LAGS = (1, 2, 3, 7, 14, 28, 364)

DATA_SOURCE = "SYNTHETIC_SIH2026"

CAVEAT = (
    "SYNTHETIC, generated by ml_data_gen_sih2026.py from documented mechanisms "
    "(Ratkowsky-type bacterial growth, Q10 spoilage, HACCP rules, published Indian "
    "climatology). Models trained on it learn the generator's assumptions. This is a "
    "pipeline and calibration check, NOT evidence about a real kitchen."
)


def bundle_dir(root: Path | None = None) -> Path:
    return (root or get_paths().data_raw) / "sih2026"


def assert_no_latent(df: pd.DataFrame, feature_cols: list[str], *, table: str) -> None:
    """Fail loudly if a ``latent_`` ground-truth column is used as a feature."""
    leaked = [c for c in feature_cols if c.startswith("latent_")]
    if leaked:
        raise AssertionError(
            f"{table}: latent ground-truth column(s) {leaked} were passed as features. "
            "The data dictionary forbids this; they exist only to score the model."
        )
    unknown = [c for c in feature_cols if c not in df.columns]
    if unknown:
        raise AssertionError(f"{table}: feature column(s) not present in the loaded table: {unknown}")


def load_demand(root: Path | None = None) -> pd.DataFrame:
    """demand_daily.csv, cleaned, with censored/closed rows marked (not silently dropped)."""
    path = bundle_dir(root) / "demand_daily.csv"
    df = pd.read_csv(path, parse_dates=["date"])

    dq_counts = df["dq_flag"].value_counts().to_dict()
    bad = df["dq_flag"].isin(DEMAND_BAD_DQ)
    df = df.loc[~bad].copy()

    # Duplicates are whole-row repeats; the flag already caught them but be explicit.
    df = df.drop_duplicates(subset=["kitchen_id", "category", "date"], keep="first")

    df["censored_stockout"] = ((df["stockout_flag"] == 1) & (df["is_closed"] == 0)).astype(int)
    df["closed"] = (df["is_closed"] == 1).astype(int)
    df["outage"] = (df["outage_flag"] == 1).astype(int)

    # Weather is missing ~1% by design.  Keep the NaN and add explicit flags so the
    # model can learn "weather unknown" rather than being handed a fabricated value.
    for col in ("temp_c", "humidity_pct", "rain_mm"):
        df[f"{col}_missing"] = df[col].isna().astype(int)

    df["is_festival"] = (df["festival_name"].fillna("").str.len() > 0).astype(int)
    df["price_index"] = df["unit_price_inr"] / df["base_price_inr"].clip(lower=1e-6)

    df["data_source"] = DATA_SOURCE
    df.attrs["dq_dropped"] = dq_counts
    df.attrs["caveat"] = CAVEAT
    LOG.info("demand: %s rows after cleaning (dq dropped %d)", f"{len(df):,}", int(bad.sum()))
    return df


def demand_features(df: pd.DataFrame) -> list[str]:
    """Feature list for the demand model: known-ahead-of-time columns + lags."""
    cat = ["kitchen_id", "category", "kitchen_type", "holiday_type", "city"]
    cal = [
        "day_of_week", "day_of_month", "month", "week_of_year", "is_weekend", "is_holiday",
        "is_holiday_eve", "days_to_next_holiday", "days_since_last_holiday", "ipl_match_day",
        "academic_break", "is_festival", "promo_discount_pct", "special_menu_flag",
        "unit_price_inr", "price_index", "capacity_meals_day",
        "temp_c", "humidity_pct", "rain_mm", "temp_c_missing", "humidity_pct_missing", "rain_mm_missing",
    ]
    return cat + cal


def add_demand_lags(df: pd.DataFrame) -> pd.DataFrame:
    """Lagged and rolling features, grouped by kitchen x category, strictly backward.

    Every shift/rolling is ``.shift(1)``-based so no row can see its own target --
    the classic leakage that flatters a demand model.
    """
    df = df.sort_values(["kitchen_id", "category", "date"]).reset_index(drop=True)
    g = df.groupby(["kitchen_id", "category"], observed=True)["units_sold"]
    for lag in DEMAND_LAGS:
        df[f"lag_{lag}"] = g.shift(lag)
    df["roll_same_dow"] = df[["lag_7", "lag_14", "lag_28"]].mean(axis=1)
    df["roll_28"] = g.transform(lambda s: s.shift(1).rolling(28, min_periods=7).mean())
    df["roll_std_28"] = g.transform(lambda s: s.shift(1).rolling(28, min_periods=14).std())
    # Short-horizon level.  The weekly lags alone leave the model blind to what the
    # series did YESTERDAY, which is most of the signal on a canteen daily count --
    # residual error was concentrated on weekends, where a level shift costs most.
    df["roll_7"] = g.transform(lambda s: s.shift(1).rolling(7, min_periods=2).mean())
    # Exponentially weighted means: short memory, so they track a drifting level
    # that a 28-day window lags behind by two weeks.
    for span in (7, 28):
        df[f"ewm_{span}"] = g.transform(
            lambda s, span=span: s.shift(1).ewm(span=span, adjust=False).mean()
        )
    for col in ("lag_7", "lag_14", "lag_28", "roll_same_dow"):
        df[f"{col}_r"] = df[col] / df["roll_28"].clip(lower=1e-6)
    # Scale-free versions of the new features, so one big kitchen cannot dominate
    # the loss purely through its volume.
    for col in ("roll_7", "ewm_7", "ewm_28"):
        df[f"{col}_r"] = df[col] / df["roll_28"].clip(lower=1e-6)
    # Short-vs-long trend: is this series rising or falling right now?
    df["trend_7_28"] = df["roll_7"] / df["roll_28"].clip(lower=1e-6)
    # Day-of-week interacts with kitchen type (a canteen and a restaurant do not
    # share a weekend curve) and with category.
    df["dow_kitchen_type"] = (
        df["day_of_week"].astype(str) + "_" + df["kitchen_type"].astype(str)
    )
    df["dow_category"] = df["day_of_week"].astype(str) + "_" + df["category"].astype(str)
    return df


def load_batches(root: Path | None = None) -> pd.DataFrame:
    """food_batches.csv -- the table behind BOTH the fusion and shelf-life models."""
    path = bundle_dir(root) / "food_batches.csv"
    df = pd.read_csv(path, parse_dates=["prep_timestamp"])

    dq_counts = df["dq_flag"].value_counts().to_dict()
    bad = df["dq_flag"].isin(BATCH_BAD_DQ)
    df = df.loc[~bad].copy()
    df = df.drop_duplicates(subset=["batch_id"], keep="first")

    df["hours_since_prep_missing"] = df["hours_since_prep"].isna().astype(int)
    df["photo_missing"] = df["cv_spoilage_prob"].isna().astype(int)
    df["voc_missing"] = df["voc_index"].isna().astype(int)
    df["odor_missing"] = df["odor_score"].isna().astype(int)
    df["logger_missing"] = df["storage_temp_c_mean"].isna().astype(int)
    # Manual probe reading is a fallback observation; record whether it exists.
    df["probe_present"] = df["manual_probe_temp_c"].notna().astype(int)

    df["data_source"] = DATA_SOURCE
    df.attrs["dq_dropped"] = dq_counts
    df.attrs["caveat"] = CAVEAT
    LOG.info("batches: %s rows after cleaning (dq dropped %d)", f"{len(df):,}", int(bad.sum()))
    return df


def batch_features(df: pd.DataFrame, *, for_shelf_life: bool = False) -> list[str]:
    """Numeric + categorical features.

    ``for_shelf_life`` drops the smell/gas channels.  Rationale: remaining life is a
    *time-and-temperature* quantity, and letting the model read spoilage sensors for
    it would quietly answer the question with the answer -- the same leak that made the
    old simulated CV column an oracle.  Safety fusion legitimately uses them, because
    asking "is this safe to give away" and "how long is it good" are different questions.
    """
    numeric = [
        "hours_since_prep", "minutes_in_danger_zone", "storage_temp_c_max", "storage_temp_c_mean",
        "storage_temp_c_min", "cooling_time_hr", "reheat_count", "handler_hygiene_score",
        "kitchen_audit_score", "packaging_integrity", "quantity_kg", "ambient_temp_c",
        "humidity_pct", "water_activity", "ph", "manual_probe_temp_c", "cooked_core_temp_c",
        "freeze_thaw_cycles", "hour_of_day", "month",
        "hours_since_prep_missing", "logger_missing", "probe_present",
    ]
    if not for_shelf_life:
        numeric += ["cv_spoilage_prob", "voc_index", "odor_score", "photo_missing",
                    "voc_missing", "odor_missing"]
    cats = ["storage_type", "packaging", "cooling_method", "source_stage", "category",
            "kitchen_type", "meal_period", "photo_quality"]
    return numeric + cats


#: Monotone constraints: (feature, +1/-1/0).  Safety physics must not be learnable away.
SAFETY_MONOTONE = {
    "hours_since_prep": 1,
    "minutes_in_danger_zone": 1,
    "storage_temp_c_max": 1,
    "storage_temp_c_mean": 1,
    "cooling_time_hr": 1,
    "reheat_count": 1,
    "handler_hygiene_score": -1,
    "kitchen_audit_score": -1,
    "packaging_integrity": -1,
    "cv_spoilage_prob": 1,
    "voc_index": 1,
    "odor_score": 1,
}


def load_sensors(root: Path | None = None) -> pd.DataFrame:
    """sensor_readings.csv.  Keeps ``dq_flag=data_gap`` rows but excludes them from scoring.

    A data gap has a NaN temperature and is explicitly NOT an anomaly, so it must not
    be counted as a false alarm either.
    """
    path = bundle_dir(root) / "sensor_readings.csv"
    df = pd.read_csv(path, parse_dates=["timestamp"])
    df = df.sort_values(["sensor_id", "timestamp"]).reset_index(drop=True)
    df["is_data_gap"] = df["dq_flag"].isin(SENSOR_BAD_DQ)
    df["data_source"] = DATA_SOURCE
    df.attrs["caveat"] = CAVEAT
    LOG.info("sensors: %s rows, %d units, %d data-gap rows", f"{len(df):,}", df.sensor_id.nunique(), int(df.is_data_gap.sum()))
    return df


def load_routing(root: Path | None = None) -> pd.DataFrame:
    path = bundle_dir(root) / "routing_nodes.csv"
    df = pd.read_csv(path)
    df.attrs["caveat"] = CAVEAT
    LOG.info("routing: %s rows across %d instances", f"{len(df):,}", df.instance_id.nunique())
    return df


def load_kitchens(root: Path | None = None) -> pd.DataFrame:
    path = bundle_dir(root) / "kitchens.csv"
    return pd.read_csv(path)


def report(root: Path | None = None) -> dict:
    """Load everything and summarise -- the sanity table a reviewer should see first."""
    d = load_demand(root)
    d2 = add_demand_lags(d)
    b = load_batches(root)
    s = load_sensors(root)
    r = load_routing(root)
    k = load_kitchens(root)

    usable = d2[(d2["closed"] == 0) & (d2["censored_stockout"] == 0) & d2["roll_28"].notna()
                & d2["roll_28"].gt(0) & d2["units_sold"].notna()]
    info = {
        "demand_rows": int(len(d)),
        "demand_usable_rows": int(len(usable)),
        "demand_date_range": [str(d["date"].min().date()), str(d["date"].max().date())],
        "demand_kitchens": int(d.kitchen_id.nunique()),
        "demand_censored_rows": int(d["censored_stockout"].sum()),
        "demand_closed_rows": int(d["closed"].sum()),
        "demand_dq_counts": {k2: int(v) for k2, v in d.attrs.get("dq_dropped", {}).items()},
        "batch_rows": int(len(b)),
        "batch_unsafe_rate": float(b["unsafe_for_redistribution"].mean()),
        "batch_shelf_life_zero_rate": float((b["remaining_shelf_life_hr"] == 0).mean()),
        "batch_plate_waste": int((b["source_stage"] == "plate_waste").sum()),
        "batch_missing_cv": float(b["cv_spoilage_prob"].isna().mean()),
        "batch_missing_temp": float(b["storage_temp_c_mean"].isna().mean()),
        "batch_dq_counts": {k2: int(v) for k2, v in b.attrs.get("dq_dropped", {}).items()},
        "sensor_rows": int(len(s)),
        "sensor_units": int(s.sensor_id.nunique()),
        "sensor_anomaly_rate": float(s["is_anomaly"].mean()),
        "routing_instances": int(r.instance_id.nunique()),
        "kitchens": int(len(k)),
        "data_source": DATA_SOURCE,
        "caveat": CAVEAT,
    }
    return info


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Load and clean the SIH-2026 CSV bundle.")
    ap.add_argument("--root", default=None)
    ap.add_argument("--out", default=None, help="write the report JSON here")
    a = ap.parse_args(argv)

    info = report(Path(a.root) if a.root else None)
    print("SIH-2026 bundle")
    print(f"  demand   {info['demand_rows']:,} rows  usable {info['demand_usable_rows']:,}  "
          f"{info['demand_date_range'][0]}..{info['demand_date_range'][1]}  {info['demand_kitchens']} kitchens")
    print(f"          censored(stockout) {info['demand_censored_rows']:,}   closed {info['demand_closed_rows']:,}")
    print(f"  batches  {info['batch_rows']:,} rows  unsafe {info['batch_unsafe_rate']:.1%}  "
          f"zero-life {info['batch_shelf_life_zero_rate']:.1%}  plate-waste {info['batch_plate_waste']:,}")
    print(f"          missing cv {info['batch_missing_cv']:.1%}   missing temp {info['batch_missing_temp']:.1%}")
    print(f"  sensors  {info['sensor_rows']:,} rows  {info['sensor_units']} units  anomalies {info['sensor_anomaly_rate']:.1%}")
    print(f"  routing  {info['routing_instances']} instances")
    print(f"  dq demand: {info['demand_dq_counts']}")
    print(f"  dq batches: {info['batch_dq_counts']}")
    print(f"  [{info['data_source']}] {CAVEAT}")

    out = Path(a.out) if a.out else (bundle_dir(Path(a.root) if a.root else None) / "bundle.report.json")
    save_json(out, info)
    print(f"  wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())