DROP TRIGGER IF EXISTS production_updated_at ON production;
DROP TRIGGER IF EXISTS attendance_updated_at ON attendance;
DROP TRIGGER IF EXISTS meals_updated_at ON meals;
DROP TRIGGER IF EXISTS waste_updated_at ON waste;
DROP TRIGGER IF EXISTS routes_updated_at ON routes;
DROP TRIGGER IF EXISTS matches_updated_at ON matches;
DROP TRIGGER IF EXISTS surplus_updated_at ON surplus_batches;
DROP TRIGGER IF EXISTS recipients_updated_at ON recipients;
DROP TRIGGER IF EXISTS kitchens_updated_at ON kitchens;
DROP TRIGGER IF EXISTS users_updated_at ON users;
DROP TABLE IF EXISTS route_stops;
DROP TABLE IF EXISTS routes;
DROP TABLE IF EXISTS matches;
DROP TABLE IF EXISTS surplus_batches;
DROP TABLE IF EXISTS waste;
DROP TABLE IF EXISTS production;
DROP TABLE IF EXISTS attendance;
DROP TABLE IF EXISTS meals;
ALTER TABLE users DROP CONSTRAINT IF EXISTS users_recipient_id_fkey;
DROP TABLE IF EXISTS recipients;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS kitchens;
DROP TABLE IF EXISTS organisations;
DROP FUNCTION IF EXISTS set_updated_at();
